name: getx_news_app
description: auto generate charging description

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^1.0.4
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  get: ^4.6.1
  get_storage: ^2.0.3
  webview_flutter: ^3.0.2
  conditional_builder_null_safety: ^0.0.6
  date_time_format: ^2.0.1
  font_awesome_flutter: ^10.1.0
  circular_reveal_animation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
